# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2025 Cory Parent <goedelsoup+waveform@goedelsoup.io>
version: "2"
run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - govet
    # - errcheck # todo: reenable this
    - staticcheck
    - ineffassign
    - unused
    - misspell
    # - gosec # todo: reenable this

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
